erDiagram
    CUSTOMER
    ACCOUNT
    PAYMENTACCOUNT
    SAVINGSACCOUNT
    TRANSACTION
    DEPOSIT

    CUSTOMER ||--o{ ACCOUNT : owns
    ACCOUNT ||--|| PAYMENTACCOUNT : is_a
    ACCOUNT ||--|| SAVINGSACCOUNT : is_a
    PAYMENTACCOUNT ||--o{ TRANSACTION : initiates
    SAVINGSACCOUNT ||--o{ DEPOSIT : receives
